HAI 1.2

O HAI IM LIST

	I HAS A LENGTH ITZ 0

	HOW IZ I PUSHING YR ITEM
		ME HAS A SRS ME'Z LENGTH ITZ ITEM
		ME'Z LENGTH R SUM OF ME'Z LENGTH AN 1
	IF U SAY SO

	HOW IZ I GETTING YR INDEX
		DIFFRINT INDEX AN BIGGR OF INDEX AN ME'Z LENGTH, O RLY?
			YA RLY
				FOUND YR ME'Z SRS INDEX
		OIC

		
	IF U SAY SO

	HOW IZ I PUTTING YR INDEX AN YR ITEM
		DIFFRINT INDEX AN BIGGR OF INDEX AN ME'Z LENGTH, O RLY?
			YA RLY
				ME'Z INDEX R ITEM
		OIC
	IF U SAY SO
KTHX

LIST IZ GETTING YR 2 MKAY

KTHXBYE