HAI 1.2

HOW IZ I POWERING YR BASE AN YR POWER
	BOTH SAEM POWER AN 0, O RLY?
		YA RLY, FOUND YR 1
	OIC

	I HAS A VALUE ITZ BASE
	IM IN YR PFUNC UPPIN YR I TIL BOTH SAEM I AN DIFF OF POWER AN 1
		VALUE R PRODUKT OF VALUE AN BASE
	IM OUTTA YR PFUNC

	FOUND YR VALUE
IF U SAY SO

KTHXBYE