test1:
	go run parse.go test.txt | lci part1.lol

part1:
	go run parse.go input.txt | lci part1.lol
    
test2:
	go run parse.go test.txt | lci part2.lol

part2:
	go run parse.go input.txt | lci part2.lol